spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;Mode=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always

mybatis:
  config-location: classpath:/mybatis-config.xml

jwt:
  header: Authorization
  secret: and0LXN0dWR5LXJlbm9yaXMtc3R1ZHktamRuYzctaG9tZXdvcmtwcm9qZWN0LWtpbWJ5dW5nanVuLW15YmF0aXMtY29wLWxldGdvcGxhc2UtdGFtbmE3a2JqQGdtYWlsLmNvbQ #base64 encoding한 값임 - jwt-study-renoris-study-jdnc7-homeworkproject-kimbyungjun-mybatis-cop-letgoplase-tamna7kbj@gmail.com
  # 키가 256 bit보다 커야함 낮으면 weakKeyException 이 나타남
  token-validity-in-seconds: 84000 #토큰만료시간
