spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;Mode=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      schema: schema.sql
  sql:
    init:
      mode: always
