
INSERT INTO "USER" (USER_NAME, PASSWORD, NICK_NAME, ACTIVATED) VALUES
    ( 'admin', '$2a$10$VOu0Qg.sKJniLFhJxTgRBuxSCtYTp2YmyuZZCSNothccUcC3eA0jq', 'admin', 1),
    ( 'user2', '$2a$10$VOu0Qg.sKJniLFhJxTgRBuxSCtYTp2YmyuZZCSNothccUcC3eA0jq', 'user2', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');