CREATE TABLE USER (USER_ID int auto_increment, USERNAME varchar(50) unique, PASSWORD varchar(100), NICKNAME varchar(50), ACTIVATED TiNYINT);
CREATE TABLE AUTHORITY (AUTHORITY_NAME varchar(50));
CREATE TABLE USER_AUTHORITY (USER_ID int, AUTHORITY_NAME varchar(50),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
                             FOREIGN KEY (AUTHORITY_NAME) REFERENCES AUTHORITY(AUTHORITY_NAME) ON DELETE CASCADE);
